name: CI macOS

on: push

jobs:
  test:
    name: Test job
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Run CI task
        run: |
          make test
